name: PyLint
on: push
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Python lint libraries
        run: |
          pip install autoflake isort black
      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
          
          
          # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:   
          commit_message: "pylint: auto fixes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: TeamXPandaUserbot
          commit_user_email: 1319106+TeamXPandaUserbot@users.noreply.github.comb.com
          commit_author: TeamXPandaUserbot <132319106+TeamXPandaUserbot@users.noreply.github.com>
